name = "chart-kit"
version = "0.1.0"
defaultTargets = ["ChartKit"]
testDriver = "ChartKitTests"

[[require]]
name = "proofwidgets"
git = "https://github.com/leanprover-community/ProofWidgets4"
rev = "106ff4fafc74ef4ac99d81dbf3ab399118f497a5"

[[lean_lib]]
name = "ChartKit"

[[lean_lib]]
name = "ChartKitTests"
