name = "expr-xray"
version = "0.1.0"
defaultTargets = ["ExprXRay"]
testDriver = "ExprXRayTests"

[[require]]
name = "proofwidgets"
git = "https://github.com/leanprover-community/ProofWidgets4"
rev = "6e311e2a844da9b2cc3971187df2fe0066947b93"

[[lean_lib]]
name = "ExprXRay"

[[lean_lib]]
name = "ExprXRayTests"
