#!/usr/bin/env node
// wrangler-config.mjs — write or check a wrangler config against infra/deploy.env (+ env overrides).
//
//   node scripts/lib/wrangler-config.mjs write <config> [--assets <dir>]   create <config> from wrangler.toml.example
//   node scripts/lib/wrangler-config.mjs check <config> [--assets <dir>]   exit 1 unless <config> agrees
//
// The keys that must agree: name (WORKER_NAME), main (infra/worker.js), [assets] directory (<dir>, default
// out/deploy/assets), [[r2_buckets]] bucket_name (R2_BUCKET), [vars] R2_PREFIX, and run_worker_first = true (without
// it Cloudflare serves the shell before the worker and the page loses COOP/COEP). Paths in the file are relative to
// the config file's own directory (wrangler's rule), so ./wrangler.toml gets exactly the example's paths.
import fs from 'node:fs';
import path from 'node:path';
import { SC, loadDeployEnv } from './deploy-env.mjs';

const [mode, cfgArg, ...rest] = process.argv.slice(2);
if (!['write', 'check'].includes(mode) || !cfgArg) { console.error('usage: wrangler-config.mjs write|check <config> [--assets <dir>]'); process.exit(2); }
const cfg = path.resolve(cfgArg);
const assetsDir = path.resolve(SC, rest.includes('--assets') ? rest[rest.indexOf('--assets') + 1] : 'out/deploy/assets');
let E;
try { E = loadDeployEnv(); } catch (e) { console.error(`deploy config: ${e.message}`); process.exit(2); }
const relTo = (p) => { const r = path.relative(path.dirname(cfg), p).split(path.sep).join('/'); return r || '.'; };
const want = {
  name: E.WORKER_NAME, main: relTo(path.join(SC, 'infra/worker.js')), directory: relTo(assetsDir),
  bucket_name: E.R2_BUCKET, R2_PREFIX: E.R2_PREFIX, run_worker_first: 'true',
};
const lineRe = (k) => new RegExp(`^(${k}\\s*=\\s*)("[^"]*"|true|false)\\s*$`, 'm');
const read = (src, k) => { const m = lineRe(k).exec(src); return m ? m[2].replace(/^"|"$/g, '') : undefined; };

if (mode === 'write') {
  if (fs.existsSync(cfg)) { console.error(`${cfgArg} exists: not overwriting (use 'check')`); process.exit(2); }
  let src = fs.readFileSync(path.join(SC, 'wrangler.toml.example'), 'utf8');
  for (const [k, v] of Object.entries(want)) {
    if (!lineRe(k).test(src)) { console.error(`wrangler.toml.example has no '${k} = …' line`); process.exit(1); }
    src = src.replace(lineRe(k), (_, lhs) => `${lhs}${k === 'run_worker_first' ? v : JSON.stringify(v)}`);
  }
  src = src.replace(/^# TEMPLATE\..*$/m, `# GENERATED by scripts/lib/wrangler-config.mjs from wrangler.toml.example + infra/deploy.env (${new Date().toISOString().slice(0, 10)}).`);
  fs.mkdirSync(path.dirname(cfg), { recursive: true });
  fs.writeFileSync(cfg, src);
  console.log(`wrote ${cfgArg}: ${Object.entries(want).map(([k, v]) => `${k}=${JSON.stringify(v)}`).join(' ')}`);
}
const src = fs.readFileSync(cfg, 'utf8');
const bad = Object.entries(want).filter(([k, v]) => read(src, k) !== v);
for (const [k, v] of bad) console.log(`FAIL ${cfgArg}: ${k} = ${JSON.stringify(read(src, k))}, want ${JSON.stringify(v)} (infra/deploy.env / environment)`);
if (bad.length) { console.log(`WRANGLER-CONFIG MISMATCH ${cfgArg}: fix the file or the variables; the bucket and prefix must equal the upload's`); process.exit(1); }
console.log(`WRANGLER-CONFIG OK ${cfgArg}: worker ${want.name}, bucket ${want.bucket_name}, R2_PREFIX ${JSON.stringify(want.R2_PREFIX)}, assets ${want.directory}, run_worker_first`);
